module.exports = {
  purge: {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    safelist: [ 'bg-blue-500', 
                'bg-blue-500/75', 
                'border-blue-500', 
                'group-hover:border-blue-500', 
                'text-blue-500', 
                'bg-pink-400', 
                'bg-pink-400/75', 
                'border-pink-400', 
                'group-hover:border-pink-400', 
                'text-pink-400', 
                'bg-pink-500',
                'bg-pink-500/75',
                'border-pink-500',
                'group-hover:border-pink-500',
                'text-pink-500',
                'bg-green-600',
                'bg-green-600/75',
                'border-green-600',
                'group-hover:border-green-600',
                'text-green-600',
                'bg-yellow-500',
                'bg-yellow-500/75',
                'bg-yellow-600',
                'bg-yellow-600/75',
                'border-yellow-500',
                'border-yellow-600',
                'group-hover:border-yellow-500',
                'group-hover:border-yellow-600',
                'text-yellow-500',
                'text-yellow-600',
                'bg-purple-500',
                'bg-purple-500/75',
                'bg-purple-600',
                'bg-purple-600/75',
                'border-purple-500',
                'border-purple-600',
                'group-hover:border-purple-500',
                'group-hover:border-purple-600',
                'text-purple-500',
                'text-purple-600',
                'bg-red-700',
                'bg-red-700/75',
                'bg-red-400',
                'bg-red-400/75',
                'border-red-700',
                'border-red-400',
                'group-hover:border-red-700',
                'group-hover:border-red-400',
                'text-red-700',
                'text-red-400',
                'bg-gray-700',
                'bg-gray-700/75',
                'border-gray-700',
                'group-hover:border-gray-700',
                'text-gray-700',
                'bg-gray-800',
                'bg-gray-800/75',
                'border-gray-800',
                'group-hover:border-gray-800',
                'text-gray-800',
                'bg-gray-500',
                'bg-gray-500/75',
                'border-gray-500',
                'text-gray-500',
                'bg-gray-400',
                'bg-gray-400/75',
                'border-gray-400',
                'group-hover:border-gray-400',
                'text-gray-400',
                'shadow-green-500/50',
                'shadow-red-500/50',
                'shadow-blue-500/50',
                'shadow-yellow-500/50',
                'pl-3',
                'pr-3',
                'pl-10',
                'pr-10',
                'group',
                'group-hover:bg-gray-600',
                'group-hover:bg-gray-200',
                'bg-gray-600',
                'bg-gray-200',
                "black",
                "white"
              ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {
      rotate: [ 'group-hover', 'hover', 'focus' ],
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
